$palette = @{
	fg        = "#5a5448" # main text color
	bg        = "#faf9f5" # panel background
	hl        = "#8b6e3d" # match highlight (search match)
	fgPlus    = "#4e4740" # selected line fg (bright)
	bgPlus    = "#d8d4c5" # selected line background (active)
	hlPlus    = "#6d5530" # selected match highlight (search current)
	info      = "#4a7d9e" # info line
	prompt    = "#726b5e" # prompt symbol (bright)
	pointer   = "#6d5530" # current selection arrow (search current)
	marker    = "#8b6e3d" # multi-select marker (search match)
	spinner   = "#e3eef5" # spinner while searching (muted)
	header    = "#4e4740" # header lines (bright)
	border    = "#e8e5da" # border color (subtle edge)
	label     = "#726b5e" # panel titles (bright)
	query     = "#8b6e3d" # search text (main fg)
	gutter    = "#faf9f5" # pointer area (bg)
	separator = "#d8d4c5" # line between list and prompt (border)
	scrollbar = "#d8d4c5" # scroll bar in search list (active)
	disabled  = "#8d8679" # disabled/nontext
}

$env:FZF_DEFAULT_OPTS = @"
--color=fg:$($palette.fg),fg+:$($palette.fgPlus)
--color=bg:$($palette.bg),bg+:$($palette.bgPlus)
--color=hl:$($palette.hl),hl+:$($palette.hlPlus)
--color=info:$($palette.info),marker:$($palette.marker)
--color=prompt:$($palette.prompt),spinner:$($palette.spinner)
--color=pointer:$($palette.pointer),header:$($palette.header)
--color=gutter:$($palette.gutter),border:$($palette.border)
--color=separator:$($palette.separator),scrollbar:$($palette.scrollbar)
--color=preview-border:$($palette.border),preview-scrollbar:$($palette.scrollbar)
--color=preview-label:$($palette.label),label:$($palette.label)
--color=query:$($palette.query),disabled:$($palette.disabled)
--border=sharp
--border-label=" fzf "
--border-label-pos="0"
--preview-window="border-sharp"
--margin=1
--padding=0
--prompt="❯ "
--marker="✓"
--pointer="❯"
--separator="─"
--scrollbar="│"
--info="right"
--height="40%"
--bind="ctrl-/:toggle-preview"
--bind="ctrl-u:preview-half-page-up"
--bind="ctrl-d:preview-half-page-down"
--bind="ctrl-f:preview-page-down"
--bind="ctrl-b:preview-page-up"
--bind="shift-up:preview-up"
--bind="shift-down:preview-down"
"@
