$palette = @{
	fg        = "#4e5e71" # ui.fg[3] - main text color
	bg        = "#1e2836" # ui.bg[3] - panel background
	hl        = "#00b0f7" # search.fg[1] - match highlight (search match)
	fgPlus    = "#788aa1" # ui.fg[5] - selected line fg (bright)
	bgPlus    = "#2b394d" # ui.bg[4] - selected line background (active)
	hlPlus    = "#ff8d4d" # search.fg[2] - selected match highlight (search current)
	info      = "#00c4d6" # msg[3] - info line
	prompt    = "#60738a" # ui.fg[4] - prompt symbol (bright)
	pointer   = "#ff8d4d" # search.fg[2] - current selection arrow (search current)
	marker    = "#00b0f7" # search.fg[1] - multi-select marker (search match)
	spinner   = "#374250" # ui.fg[1] - spinner while searching (muted)
	header    = "#788aa1" # ui.fg[5] - header lines (bright)
	border    = "#2b394d" # ui.bg[4] - border color (subtle edge)
	label     = "#788aa1" # ui.fg[5] - panel titles (bright)
	query     = "#4e5e71" # ui.fg[3] - search text (main fg)
	gutter    = "#1e2836" # ui.bg[3] - pointer area (bg)
	separator = "#2b394d" # ui.bg[4] - line between list and prompt (border)
	scrollbar = "#2b394d" # ui.bg[4] - scroll bar in search list (active)
	disabled  = "#424f5f" # ui.fg[2] - disabled/nontext
}

$env:FZF_DEFAULT_OPTS = @"
--color=fg:$($palette.fg),fg+:$($palette.fgPlus)
--color=bg:$($palette.bg),bg+:$($palette.bgPlus)
--color=hl:$($palette.hl),hl+:$($palette.hlPlus)
--color=info:$($palette.info),marker:$($palette.marker)
--color=prompt:$($palette.prompt),spinner:$($palette.spinner)
--color=pointer:$($palette.pointer),header:$($palette.header)
--color=gutter:$($palette.gutter),border:$($palette.border)
--color=separator:$($palette.separator),scrollbar:$($palette.scrollbar)
--color=preview-border:$($palette.border),preview-scrollbar:$($palette.scrollbar)
--color=preview-label:$($palette.label),label:$($palette.label)
--color=query:$($palette.query),disabled:$($palette.disabled)
--border=sharp
--border-label=" fzf "
--border-label-pos="0"
--preview-window="border-sharp"
--margin=1
--padding=0
--prompt="❯ "
--marker="✓"
--pointer="❯"
--separator="─"
--scrollbar="│"
--info="right"
--height="40%"
--bind="ctrl-/:toggle-preview"
--bind="ctrl-u:preview-half-page-up"
--bind="ctrl-d:preview-half-page-down"
--bind="ctrl-f:preview-page-down"
--bind="ctrl-b:preview-page-up"
--bind="shift-up:preview-up"
--bind="shift-down:preview-down"
"@
