$palette = @{
	fg        = "#8a9aa1" # main text color
	bg        = "#141618" # panel background
	hl        = "#bfa070" # match highlight (search match)
	fgPlus    = "#b0c5cb" # selected line fg (bright)
	bgPlus    = "#1e262a" # selected line background (active)
	hlPlus    = "#d0b185" # selected match highlight (search current)
	info      = "#7a94ab" # info line
	prompt    = "#8a9aa1" # prompt symbol (bright)
	pointer   = "#d0b185" # current selection arrow (search current)
	marker    = "#bfa070" # multi-select marker (search match)
	spinner   = "#1e2a30" # spinner while searching (muted)
	header    = "#b0c5cb" # header lines (bright)
	border    = "#1e262a" # border color (subtle edge)
	label     = "#8a9aa1" # panel titles (bright)
	query     = "#bfa070" # search text (main fg)
	gutter    = "#141618" # pointer area (bg)
	separator = "#1e262a" # line between list and prompt (border)
	scrollbar = "#1e262a" # scroll bar in search list (active)
	disabled  = "#626e72" # disabled/nontext
}

$env:FZF_DEFAULT_OPTS = @"
--color=fg:$($palette.fg),fg+:$($palette.fgPlus)
--color=bg:$($palette.bg),bg+:$($palette.bgPlus)
--color=hl:$($palette.hl),hl+:$($palette.hlPlus)
--color=info:$($palette.info),marker:$($palette.marker)
--color=prompt:$($palette.prompt),spinner:$($palette.spinner)
--color=pointer:$($palette.pointer),header:$($palette.header)
--color=gutter:$($palette.gutter),border:$($palette.border)
--color=separator:$($palette.separator),scrollbar:$($palette.scrollbar)
--color=preview-border:$($palette.border),preview-scrollbar:$($palette.scrollbar)
--color=preview-label:$($palette.label),label:$($palette.label)
--color=query:$($palette.query),disabled:$($palette.disabled)
--border=sharp
--border-label=" fzf "
--border-label-pos="0"
--preview-window="border-sharp"
--margin=1
--padding=0
--prompt="❯ "
--marker="✓"
--pointer="❯"
--separator="─"
--scrollbar="│"
--info="right"
--height="40%"
--bind="ctrl-/:toggle-preview"
--bind="ctrl-u:preview-half-page-up"
--bind="ctrl-d:preview-half-page-down"
--bind="ctrl-f:preview-page-down"
--bind="ctrl-b:preview-page-up"
--bind="shift-up:preview-up"
--bind="shift-down:preview-down"
"@
