"$schema" = 'https://starship.rs/config-schema.json'

[aws]
symbol = "☁️ "

[buf]
symbol = "🥣 "

[bun]
symbol = "🍞 "

[c]
symbol = "© "

[cpp]
symbol = "C++ "

[cmake]
symbol = "△ "

[conda]
symbol = "◯ "

[crystal]
symbol = "💎 "

[dart]
symbol = "🎯 "

[deno]
symbol = "🦕 "

[directory]
read_only = " 🔒"

[docker_context]
symbol = "🐋 "

[elixir]
symbol = "💧 "

[elm]
symbol = "🌳 "

[fennel]
symbol = "🌱 "

[fortran]
symbol = "F "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "☁️ "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = ' 🏷️ '

[golang]
symbol = "🐹 "

[gradle]
symbol = "🐘 "

[guix_shell]
symbol = "❄️ "

[haskell]
symbol = "λ "

[haxe]
symbol = "HX "

[hg_branch]
symbol = "☿ "

[hostname]
ssh_symbol = "🌐 "

[java]
symbol = "☕ "

[julia]
symbol = "⊙ "

[kotlin]
symbol = "K "

[lua]
symbol = "🌙 "

[memory_usage]
symbol = "🧠 "

[meson]
symbol = "M "

[nim]
symbol = "👑 "

[nix_shell]
symbol = "❄️ "

[nodejs]
symbol = "⬢ "

[ocaml]
symbol = "🐫 "

[os.symbols]
Alpaquita = "A "
Alpine = "🏔️ "
AlmaLinux = "A "
Amazon = "☁️ "
Android = "🤖 "
AOSC = "A "
Arch = "A "
Artix = "A "
CachyOS = "C "
CentOS = "C "
Debian = "🌀 "
DragonFly = "🐉 "
Emscripten = "E "
EndeavourOS = "E "
Fedora = "f "
FreeBSD = "😈 "
Garuda = "🦅 "
Gentoo = "G "
HardenedBSD = "H "
Illumos = "I "
Kali = "K "
Linux = "🐧 "
Mabox = "M "
Macos = "🍎 "
Manjaro = "M "
Mariner = "M "
MidnightBSD = "M "
Mint = "M "
NetBSD = "N "
NixOS = "❄️ "
Nobara = "N "
OpenBSD = "🐡 "
openSUSE = "🦎 "
OracleLinux = "O "
Pop = "P "
Raspbian = "🍓 "
Redhat = "🎩 "
RedHatEnterprise = "🎩 "
RockyLinux = "R "
Redox = "R "
Solus = "S "
SUSE = "S "
Ubuntu = "U "
Unknown = "❓ "
Void = "V "
Windows = "🪟 "

[package]
symbol = "📦 "
style = "bold yellow"

[perl]
symbol = "🐪 "

[php]
symbol = "🐘 "

[pijul_channel]
symbol = " "

[pixi]
symbol = "📦 "

[python]
symbol = "🐍 "

[rlang]
symbol = "R "

[ruby]
symbol = "💎 "

[rust]
symbol = "🦀 "

[scala]
symbol = "S "

[status]
symbol = "✘ "

[swift]
symbol = "🐦 "

[xmake]
symbol = "X "

[zig]
symbol = "Z "
