theme_background = false
rounded_corners = true
color_theme = "default"
vim_keys = true
terminal_sync = true
background_update = true
base_10_sizes = false
graph_symbol = "braille"
update_ms = 2000
cpu_update_ms = 0
mem_update_ms = 0
disk_update_ms = 0
net_update_ms = 0
gpu_update_ms = 0
proc_update_ms = 0
graph_symbol_cpu = "default"
cpu_graph_upper = "user"
cpu_graph_lower = "system"
cpu_invert_lower = true
cpu_single_graph = false
cpu_auto_scale = true
check_temp = true
show_coretemp = true
temp_scale = "celsius"
show_cpu_freq = true
custom_cpu_name = ""
show_cpu_watts = true
show_swap = true
graph_symbol_net = "default"
swap_upload_download = false
net_download = 100
net_upload = 100
proc_aggregate = false
proc_colors = true
proc_gradient = true
proc_mem_bytes = true
graph_symbol_disk = "default"
show_io_stat = true
io_graph_combined = false
disk_io_mode = false
disk_filter = []
log_level = "warn"
proc_tree = false
proc_reversed = true
proc_per_core = false
proc_sorting = "cpu"
proc_filter = ""
io_mode = false
net_auto = true
net_sync = false
net_iface = "auto"
gpu_iface = "auto"
show_statusbar = true
statusbar_show_menu = true
statusbar_show_preset = true
statusbar_show_update_interval = true
statusbar_show_uptime = true
statusbar_show_clock = true
statusbar_clock_format = "%T"
preset = "all"
custom_layout = "vstack(cpu, hstack(40:vstack(gpu, mem, net, disk), 60:proc), statusbar)"
hidden_widgets = []
